#!/bin/bash

echo "=================================================="
echo "  Script para Actualizar product_permissions"
echo "=================================================="
echo ""
echo "IMPORTANTE: Este script te guiará para actualizar el módulo."
echo ""
echo "Opción 1: Desde la interfaz de Odoo (RECOMENDADO)"
echo "  1. Ir a: Aplicaciones"
echo "  2. Quitar filtro 'Apps'"
echo "  3. Buscar: product_permissions"
echo "  4. Click en los 3 puntos (...)"
echo "  5. Click en 'Actualizar'"
echo ""
echo "Opción 2: Desde línea de comandos"
echo "  Ejecutar:"
echo "  odoo-bin -d odoo18 -u product_permissions --stop-after-init"
echo ""
echo "Opción 3: Reiniciar Odoo (aplica todos los cambios)"
echo "  sudo systemctl restart odoo"
echo ""
echo "=================================================="
echo "Después de actualizar, intenta crear una nueva venta."
echo "=================================================="
